{% set name = "lenstool" %}
{% set version = "8.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://git-cral.univ-lyon1.fr/{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8abd2cef74ef9d5cf405627e0534ae8a009cc66c4488a9977d6b768ceab1ffc

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [not win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib('c') }}   # [not win]
    - make  # [not win]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python
    - pip
    - cfitsio
    - wcslib
    - gsl
    - libblas  # [linux]
    - astropy-base
  run:
    - python
    - numpy
    - cfitsio
    - wcslib
    - gsl
    - libblas  # [linux]
    - astropy-base
    - scipy
    - emcee
    - matplotlib-base
    - corner

test:
  imports:
    - lenstool

  commands:
    - test -f $PREFIX/bin/lenstool  # [unix]

about:
  home: https://projets.lam.fr/projects/lenstool
  license: GPL-3.0-only
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: A gravitational lensing software for modeling mass distribution of galaxies and clusters (strong and weak regime).

extra:
  recipe-maintainers:
    - ejullo
