{% set name = "lenstool" %}
{% set version = "8.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://git-cral.univ-lyon1.fr/{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: f72cde38064a7bf63c5f3de0a3e3a2d28bec599f1486089714a6cbcc2c234a4a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - libtool  # [not win]
    - {{ compiler('c') }}  # [not win]
    - make  # [not win]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python
    - pip
    - cfitsio
    - wcslib
    - gsl
    - libblas  # [linux]
    - astropy
  run:
    - python
    - numpy
    - cfitsio
    - wcslib
    - gsl
    - libblas  # [linux]
    - astropy

test:
  imports:
    - lenstool

  commands:
    - test -f $PREFIX/bin/lenstool  # [unix]

about:
  home: https://projets.lam.fr/projects/lenstool
  license: GPL-3.0-only
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: A gravitational lensing software for modeling mass distribution of galaxies and clusters (strong and weak regime).

extra:
  recipe-maintainers:
    - ejullo
