{% set name = "lenstool" %}
{% set version = "8.8.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://git-cral.univ-lyon1.fr/{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5f870cabb7743b4725568375c7f71d58c6ac3556df36446a5ae2773579735c1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [not win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}  # [not win]
    - {{ stdlib("c") }}    # [not win]
    - make  # [not win]
    - pkg-config
    - autoconf
    - automake
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python
    - pip
    - setuptools
    - cfitsio
    - wcslib
    - gsl
    - libblas  # [linux]
    - astropy-base
  run:
    - python
    - numpy
    - cfitsio
    - wcslib
    - gsl
    - libblas  # [linux]
    - astropy-base
    - scipy
    - emcee
    - matplotlib-base
    - corner

test:
  imports:
    - lenstool

  commands:
    - test -f $PREFIX/bin/lenstool  # [unix]

about:
  home: https://projets.lam.fr/projects/lenstool
  license: GPL-3.0-only
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: A gravitational lensing software for modeling mass distribution of galaxies and clusters (strong and weak regime).

extra:
  recipe-maintainers:
    - ejullo
    - njzifjoiez
